name: datawatch
description: "A local monitoring dashboard with encrypted local auth."
publish_to: "none"
version: 0.2.0

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  cupertino_icons: ^1.0.8
  bcrypt: ^1.1.3
  encrypt: ^5.0.3
  flutter_secure_storage: ^9.2.4
  path_provider: ^2.1.5
  http: ^1.5.0
  socket_io_client: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/nav_logo.png
    - assets/main_logo.png